# 플레이스홀더와 변수

In [1]:
import tensorflow as tf

X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


tf.placeholder는 계산을 실행할 때 입력값을 받는 변수로 사용된다.  
None 은 크기가 정해지지 않았음을 의미한다.

In [2]:
x_data = [[1,2,3], [4,5,6]]

X 플레이스 홀더에 넣을 값을 정의해준다.  
플레이스 홀더에서 설정한 것 처럼, 두번째 차원의 요소의 갯수는 3개이다.

In [4]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

tf.Variable은 그래프를 계산하면서 최적화 할 변수이다. 이 값이 바로 신경망을 좌우한다.  
tf.random_normal은 각 변수들의 초기값을 정규분포 랜덤 값으로 초기화한다.

W는 Weight, b는 bias를 의미한다.
h(x) = WX + b의 꼴이다.

In [5]:
expr = tf.matmul(X,W) + b

입격값과 변수들을 계산할 수식을 직접 표현한다.  
tf.matmul은 행렬곱을 의미한다.

In [6]:
sess = tf.Session()

텐서플로우는 세션을 통해서 실행을 해야하기 때문에, 세션을 선언한다.

In [8]:
sess.run(tf.global_variables_initializer())

위에서 설정한 Variable 들의 값들을 초기화 하기 위해, 처음에 tf.global_variables_initializer를 한번 실행한다.

In [11]:
print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.8203623 -0.2512328]
 [ 0.6249272  1.0048796]
 [-1.9603184 -2.6991367]]
=== b ===
[[-0.4173716]
 [ 1.7854517]]
=== expr ===
[[ -5.868835   -6.7562556]
 [-10.133272  -10.389902 ]]


본 예제에서는 실제 학습을 하는 과정을 표현하지는 않았다.